name: Node.js CI

on:
  push:
    branches: [ master ]  
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GATEWAY_PORT: 3000
      USER_SERVICE_PORT: 3001
      TASKS_SERVICE_PORT: 3002
      ACTIVITY_SERVICE_PORT: 3003
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_USER: user
      MONGO_ACTIVITY_URI: ${{ secrets.MONGO_ACTIVITY_URI }}
      MONGO_TASKS_URI: ${{ secrets.MONGO_TASKS_URI }}
      MONGO_USER_URI: ${{ secrets.MONGO_USER_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
      RABBITMQ_URI: ${{ secrets.RABBITMQ_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-    

      - name: Install user-service dependencies
        working-directory: ./user-service
        run: npm ci

      - name: Install tasks-service dependencies
        working-directory: ./tasks-service
        run: npm ci  

      - name: Install activity-service dependencies
        working-directory: ./activity-service
        run: npm ci  

      - name: Install api-gateway dependencies
        working-directory: ./api-gateway
        run: npm ci  

      - name: Build Docker images
        run: docker compose build  

      - name: DEBUG - Check env vars before test step
        run: |
          echo "GATEWAY_PORT=${GATEWAY_PORT}"
          echo "USER_SERVICE_PORT=${USER_SERVICE_PORT}"
          echo "TASKS_SERVICE_PORT=${TASKS_SERVICE_PORT}"
          echo "ACTIVITY_SERVICE_PORT=${ACTIVITY_SERVICE_PORT}"
          echo "REDIS_HOST=${REDIS_HOST}"
          echo "REDIS_PORT=${REDIS_PORT}"
          echo "RABBITMQ_USER=${RABBITMQ_USER}"
          echo "MONGO_ACTIVITY_URI=${MONGO_ACTIVITY_URI}"
          echo "MONGO_TASKS_URI=${MONGO_TASKS_URI}"
          echo "MONGO_USER_URI=${MONGO_USER_URI}"
          echo "JWT_SECRET=${JWT_SECRET}"
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}"
          echo "RABBITMQ_PASS=${RABBITMQ_PASS}"
            

      - name: Run tests for api-gateway
        working-directory: ./api-gateway
        run: npm test        

      - name: Dump Docker logs on failure
        if: failure()
        run: docker compose -f ./docker-compose.yml logs